#!/bin/bash
# Bounded source-checkout cleanup. No runtime restart and no evidence/drawing removal.
set -euo pipefail
repo=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)
fail() { printf '%s\n' "$*" >&2; exit 1; }
apply=false caches=false
while [ "$#" -gt 0 ]; do
    case "$1" in
        --apply) apply=true;;
        --caches) caches=true;;
        --help)
            printf '%s\n' 'Usage: scripts/cleanup-development.sh [--apply] [--caches]' \
                'Default: preview managed packages older than seven days, retaining the newest three.' \
                'Preserves the configured package, running packages and unmarked directories.' \
                '--caches also selects both default Cargo targets (requires idle Cargo/rustc).' \
                'Drawings, configuration, migration evidence and custom target directories are untouched.'
            exit 0;;
        *) fail "Unknown cleanup option: $1";;
    esac
    shift
done
private=$repo/.inkscape-mcp-local
[ ! -L "$private" ] || fail 'Private build directory must not be a symlink.'
config=$private/setup.conf
[ ! -L "$config" ] || fail 'Configuration must not be a symlink.'
[ ! -e "$config" ] || [ -f "$config" ] || fail 'Configuration must be a regular file.'
# Fail closed if process inspection is unavailable. Inspect executable paths too.
processes=$(ps -axo comm,args) || fail 'Cannot inspect active processes; cleanup refused.'
selected= workspace=
if [ -f "$config" ]; then
    [ "$(sed -n '1p' "$config")" = inkscape-mcp-setup-v1 ] || fail 'Unknown setup configuration.'
    selected=$(sed -n '2p' "$config")
    workspace=$(sed -n '4p' "$config")
    case "$selected" in /*/bin/inkscape-mcp) ;; *) fail 'Invalid configured package path.';; esac
    case "$workspace" in /*) ;; *) fail 'Invalid configured workspace path.';; esac
fi
cache_paths=()
if [ "$caches" = true ]; then
    if printf '%s\n' "$processes" | /usr/bin/grep -Eq '(^|/)(cargo|rustc)([[:space:]]|$)'; then
        fail 'Cargo/rustc is running; cache cleanup refused.'
    fi
    for relative in rust/target rust/tooling/target; do
        path=$repo/$relative
        [ ! -L "$repo/rust" ] && [ ! -L "$repo/rust/tooling" ] && [ ! -L "$path" ] ||
            fail 'Cargo target or parent is a symlink; cache cleanup refused.'
        [ -e "$path" ] || continue
        [ -d "$path" ] && [ -f "$path/CACHEDIR.TAG" ] && [ ! -L "$path/CACHEDIR.TAG" ] ||
            fail "Unrecognized Cargo cache: $path"
        [ "$(sed -n '1p' "$path/CACHEDIR.TAG")" = 'Signature: 8a477f597d28d172789f06886806bc55' ] ||
            fail "Invalid Cargo cache marker: $path"
        case "$selected" in "$path"/*) fail 'Configured runtime uses a Cargo cache.';; esac
        case "$workspace" in "$path"|"$path"/*) fail 'Configured workspace uses a Cargo cache.';; esac
        case "$processes" in *"$path/"*) fail 'Running process uses a Cargo cache.';; esac
        cache_paths+=("$path")
    done
fi
remove() {
    local path=$1
    printf '%s %s\n' "$([ "$apply" = true ] && printf Remove || printf Would-remove)" "$path"
    [ "$apply" = false ] || rm -rf -- "$path"
}
shopt -s nullglob
entries=("$private"/build.*)
[ "${#entries[@]}" -le 10000 ] || fail 'Build inventory exceeds cleanup limit.'
# Names are generated by mktemp; never parse arbitrary directory names as records.
inventory() {
    local path name stamp
    for path in ${entries[@]+"${entries[@]}"}; do
        name=${path##*/}
        [[ "$name" =~ ^build\.[A-Za-z0-9]{6}$ ]] || continue
        [ -d "$path" ] && [ ! -L "$path" ] || continue
        [ -f "$path/.managed-build" ] && [ ! -L "$path/.managed-build" ] || continue
        [ "$(cat "$path/.managed-build")" = inkscape-mcp-managed-build-v1 ] || continue
        if [ "$(uname -s)" = Darwin ]; then
            stamp=$(stat -f %m "$path/.managed-build")
        else
            stamp=$(stat -c %Y "$path/.managed-build")
        fi
        [[ "$stamp" =~ ^[0-9]+$ ]] || fail 'Cannot read build age.'
        printf '%s %s\n' "$stamp" "$name"
    done
}
records=$(inventory | sort -rn)
rank=0
now=$(date +%s)
while read -r stamp name; do
    [ -n "$name" ] || continue
    rank=$((rank + 1))
    [ "$rank" -gt 3 ] || continue
    [ "$((now - stamp))" -ge 604800 ] || continue
    path=$private/$name
    case "$selected" in "$path"/*) continue;; esac
    case "$workspace" in "$path"|"$path"/*) continue;; esac
    case "$processes" in *"$path/"*) continue;; esac
    # Added/removed package paths (including drawings) relinquish automatic ownership.
    [ -f "$path/.managed-files" ] && [ ! -L "$path/.managed-files" ] || continue
    cmp -s "$path/.managed-files" <(cd -- "$path" && find package -print | LC_ALL=C sort) || continue
    # User additions at the staging root make ownership ambiguous; retain them.
    safe=true
    for child in "$path"/* "$path"/.[!.]* "$path"/..?*; do
        case "${child##*/}" in package|.managed-build|.managed-files) ;; *) safe=false;; esac
    done
    [ "$safe" = true ] || continue
    remove "$path"
done <<< "$records"
for path in ${cache_paths[@]+"${cache_paths[@]}"}; do remove "$path"; done
